name = Omega Child Layout
description = Simple Mobile First theme.
preview = preview.png
template = omegachild-layout

; Regions
regions[branding]       = Branding
regions[header]         = Header
regions[banner]         = Banner Area
;regions[navigation]     = Navigation bar
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
;regions[sidebar_first]  = First sidebar
;regions[sidebar_second] = Second sidebar
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/omegachild/omegachild.layout.css
